fix if

diff --git a/foreman-host-configurator/foreman-host-configurator b/foreman-host-configurator/foreman-host-configurator
--- a/foreman-host-configurator/foreman-host-configurator
+++ b/foreman-host-configurator/foreman-host-configurator
@@ -19,12 +19,12 @@ if [ ! -e "${JAR_FILE}" ] ; then
         echo "Building foreman-host-configurator..."
         mvn package -DskipTests 1> /dev/null 2> /dev/null
         if [ $? -ne 0 ] ; then
-	    echo "Failed to build foreman-host-configurator! Try to build using 'mvn clean package -DskipTests and check output."
-	    exit 1
+            echo "Failed to build foreman-host-configurator! Try to build using 'mvn clean package -DskipTests and check output."
+            exit 1
         fi
-	JAR_FILE=${SCRIPT_DIR}/target/foreman-host-configurator.jar
+        JAR_FILE=${SCRIPT_DIR}/target/foreman-host-configurator.jar
     fi
-
+fi
 
 $JAVACMD -jar "${JAR_FILE}" "$*"
 exit $?
