add more tests for foreman-host-configurator script

diff --git a/foreman-host-configurator/foreman-host-configurator b/foreman-host-configurator/foreman-host-configurator
--- a/foreman-host-configurator/foreman-host-configurator
+++ b/foreman-host-configurator/foreman-host-configurator
@@ -7,20 +7,24 @@ if [ $? -ne 0 ] ; then
 fi
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+JAR_FILE=${SCRIPT_DIR}/foreman-host-configurator.jar
 
-if [ ! -e "${SCRIPT_DIR}/target/foreman-host-configurator.jar" ] ; then
-    MVNCMD=$(which mvn 2> /dev/null)
-    if [ $? -ne 0 ] ; then
-      echo "Maven is required to build foreman-host-configurator"
-      exit 1
-    fi
-    echo "Building foreman-host-configurator..."
-    mvn clean package -DskipTests 1> /dev/null 2> /dev/null
-    if [ $? -ne 0 ] ; then
-	echo "Failed to build foreman-host-configurator! Try to build using 'mvn clean package -DskipTests and check output."
-	exit 1
+if [ ! -e "${JAR_FILE}" ] ; then
+    if [ ! -e "${SCRIPT_DIR}/target/foreman-host-configurator.jar" ] ; then
+        MVNCMD=$(which mvn 2> /dev/null)
+        if [ $? -ne 0 ] ; then
+          echo "Maven is required to build foreman-host-configurator"
+          exit 1
+        fi
+        echo "Building foreman-host-configurator..."
+        mvn clean package -DskipTests 1> /dev/null 2> /dev/null
+        if [ $? -ne 0 ] ; then
+	    echo "Failed to build foreman-host-configurator! Try to build using 'mvn clean package -DskipTests and check output."
+	    exit 1
+        fi
+	JAR_FILE=${SCRIPT_DIR}/target/foreman-host-configurator.jar
     fi
 fi
 
-$JAVACMD -jar "${SCRIPT_DIR}/target/foreman-host-configurator.jar" "$*"
+$JAVACMD -jar "${JAR_FILE}" "$*"
 exit $?
